ORTHODOX_BIBLE_VERSES = [
    ("John 3:16", "For God so loved the world that He gave His only begotten Son, that whoever believes in Him should not perish but have everlasting life."),
    ("Matthew 5:9", "Blessed are the peacemakers, for they shall be called sons of God."),
    ("Philippians 4:13", "I can do all things through Christ who strengthens me."),
    ("1 John 4:19", "We love Him because He first loved us."),
    ("Psalm 23:1", "The Lord is my shepherd; I shall not want."),
    ("Proverbs 3:5-6", "Trust in the Lord with all your heart, and lean not on your own understanding; in all your ways acknowledge Him, and He shall direct your paths."),
    ("Isaiah 40:31", "But those who wait on the Lord shall renew their strength; they shall mount up with wings like eagles, they shall run and not be weary, they shall walk and not faint."),
    ("Romans 8:28", "And we know that all things work together for good to those who love God, to those who are the called according to His purpose."),
    ("Matthew 11:28", "Come to Me, all you who labor and are heavy laden, and I will give you rest."),
    ("Psalm 118:24", "This is the day the Lord has made; we will rejoice and be glad in it."),
    ("1 Peter 5:7", "Casting all your care upon Him, for He cares for you."),
    ("Colossians 3:2", "Set your mind on things above, not on things on the earth."),
    ("James 1:2-3", "My brethren, count it all joy when you fall into various trials, knowing that the testing of your faith produces patience."),
    ("Psalm 46:10", "Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth!"),
    ("Matthew 6:33", "But seek first the kingdom of God and His righteousness, and all these things shall be added to you."),
    ("1 Thessalonians 5:16-18", "Rejoice always, pray without ceasing, in everything give thanks; for this is the will of God in Christ Jesus for you."),
    ("2 Corinthians 5:17", "Therefore, if anyone is in Christ, he is a new creation; old things have passed away; behold, all things have become new."),
    ("Ephesians 2:8-9", "For by grace you have been saved through faith, and that not of yourselves; it is the gift of God, not of works, lest anyone should boast."),
    ("John 14:6", "Jesus said to him, 'I am the way, the truth, and the life. No one comes to the Father except through Me.'"),
    ("Psalm 27:1", "The Lord is my light and my salvation; whom shall I fear? The Lord is the strength of my life; of whom shall I be afraid?")
]